### ISSUE TITLE
Consider removing support for IE8

### ISSUE THREAD

**Issue by gregtyler** [ministryofjustice/moj-frontend#481]
[Following the GOV.UK Design System's lead](https://github.com/alphagov/govuk-frontend/issues/2621) we should consider removing support for IE8. We have [a few components](https://github.com/search?q=repo%3Aministryofjustice%2Fmoj-frontend%20ie8&type=code) which make special considerations for IE8 that we should assess the validity of and remove if possible.

If the components still fundamentally work in IE8 without the considerations (even if it looks a bit ropey), we can remove them and drop IE8 support. But if they're fundamentally essential for a component to function, we'll need to talk with MOJ services about what level of support they require.

If we do drop support for IE8, then we can stop building/distributing the IE8-specific CSS file. This would need to be a major release.

**Comment by frankieroberto** [comment]
@gregtyler hi - we’re using this npm package in production on the [apply for teacher training service](https://github.com/DFE-Digital/apply-for-teacher-training).

Since upgrading to `govuk-frontend` 4.6, the MOJ frontend package is throwing warnings caused by the use of the `govuk-if-ie8` mixing, which has now been deprecated, and will be removed in v5 of govuk-frontend.

So consider this a +1 for dropping IE8 support! 😄

**Comment by gregtyler** [comment]
See #528 for more details, but as govuk-frontend v5 is removing support for IE8 we will be doing the same with our v2 (which requires govuk-frontend v5).
