### ISSUE TITLE
Scrollable area for tables and other things

### ISSUE THREAD

**Issue by adamsilver** [ministryofjustice/moj-frontend#59]
As seen here on smaller screens:

![image](https://user-images.githubusercontent.com/37163/61046591-72268780-a3d5-11e9-8c7a-77def491dc85.png)

**Comment by gregtyler** [comment]
This was raised as a problem in the recent Accessibility Audit. We should add a "Responsive table" component which can be used to wrap tables in a 100% width div with `overflow-x: auto;`. This will allow tables to be scrollable rather than overflowing outside their parent element or the page in general.

Basically, we should replicate [Boostrap's `table-responsive` class](https://getbootstrap.com/docs/4.4/content/tables/#always-responsive) but as `moj-table-responsive`.

**Comment by gregtyler** [comment]
This actually already exists as `.moj-scrollable-pane__wrapper`: I just spotted it in use on the [Filter a list](https://moj-design-system.herokuapp.com/patterns/filter-a-list) pattern.

So we just need to:
1. Test it and make any improvements
2. Document it
