### ISSUE TITLE
$string: #000000 is not a string for `quote'

### ISSUE THREAD

**Issue by rossjones** [ministryofjustice/moj-frontend#79]
### Prerequisites

* [/] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Followed all applicable steps in the debugging guide
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue doesn't exist: https://github.com/ministryofjustice/moj-frontend/issues
    * Checked that there is not already a package that provides the described functionality

Unclear where debugging guide or message board is...

### Description

When using the MoJ Design System in a rails application, and having followed the instructions ( although https://github.com/ministryofjustice/moj-frontend/blob/master/docs/installation/installing-with-npm.md suggests to `@import "node_modules/@ministryofjustice/frontend/all";` but the all file is actually in `@import "node_modules/@ministryofjustice/frontend/moj/all";`) rails complains with 

`$string: #000000 is not a string for `quote'`

This seems to be caused by the following code at https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/helpers/_colour.scss#L39

```scss
$colour: quote($colour);
```

### Steps to Reproduce

1. Install govuk design system v3
2. Follow instructions at https://github.com/ministryofjustice/moj-frontend/blob/master/docs/installation/installing-with-npm.md in a Rails app.

**Expected behaviour:** 
Page to render

**Actual behaviour:**
Rails complains about something broken in govuk's _colour.scss

```
node_modules/govuk-frontend/govuk/helpers/_colour.scss:39
node_modules/@ministryofjustice/frontend/moj/components/_all.scss:8
node_modules/@ministryofjustice/frontend/moj/all.scss:4
```

**Reproduces how often:** 

All the time

### Versions

```
"@ministryofjustice/frontend": "0.0.13-alpha",
"govuk-frontend": "^3.1.0"
```

**Comment by johnnolan** [comment]
I have the same issue here but through webpack. I believe the preprocesors Rails and Webpack use are more vigilant on what is allowed.

I believe the issue is below where the colour black is not in quotes. Changing this then allows webpack to process the styles correctly.

https://github.com/ministryofjustice/moj-frontend/blob/63906fcb3a4487768958231fe48d3842e310160f/src/moj/components/header/_header.scss#L74

I am just waiting for permissions to this repo and I will push a branch and make a PR that fixes it
