### ISSUE TITLE
Archive password reveal component

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#941]
## What
Move the password reveal documentation page on the DS doc site so it is archived along with other components. Check other archived pages to mirror the changes required (e.g. updating the caption above the H1).

Also, include a banner on the page (similar to other archived components) to direct users to the [GOV.UK Design Systems password input component](https://design-system.service.gov.uk/components/password-input/).

Also, prepare Archive space on MoJ Figma Kit in preparation to move the Password reveal component there, and decide upon a naming convention for labelling archived components.

## Why
The GOV.UK Design System has a similar component. After a mini-discovery to understand usage of the MoJ component, it has been decided to archive it.

## Who needs to be involved
- Content Designer
- Interaction Designer

### Content

- [x] Content written
- [x] Content OK-ed by 2i

### Interaction
- [x] Figma approach decided
- [x] Create branch and make changes
- [x] Create PR for review

## Done
When a PR is setup and ready for merging to main with the password reveal component moved to the archive section of the doc site and updated to reflect the need to direct users to the GOV.UK Design System component.

**Comment by helennickols** [comment]
Content stuff all sorted. I'll leave this in 'in progress' for Murray's Figma work.

**Comment by murrlipp** [comment]
I've done some testing in a temporary Figma library and here's the proposed approach:

1. Change the name of the component to '⚠️ ARCHIVED: Password reveal'.
2. Move the component page to an 'ARCHIVED COMPONENTS' section in the library:
![Image](https://github.com/user-attachments/assets/dac4bee0-72f3-4392-8544-24ad06ff2a91)
4. Hide the component from publishing.
5. Add a banner to the Figma component page containing the content written by Helen:![Image](https://github.com/user-attachments/assets/3fba2f6c-87eb-4575-98cb-3e43c41e02a2)
6. Lock the component so that it cannot be copied.

This means that:
- The component is still in the library so won't break anyone's prototypes if they're using it.
- If people search for it in the Figma assets panel, it won't appear.
- If people navigate to it via the documentation site, they'll see that it's in the 'archived' section with a banner.
- If people navigate to it via the Figma file, they'll see it's in the 'archived' section.
- We are signposting people to the relevant alternatives using the banner.

Things to be aware of:
- This won't stop people copying instances from other files and continuing to use it.
- The alternative is deleting the component, which _will_ break people's prototypes.

Proposed changes can be seen on the Figma branch here: https://www.figma.com/design/G5w7soIxqPQorICm4JsxZ9/archive-password-reveal?node-id=66-6026
